# Uncomment the next line to define a global platform for your project
# platform :ios, '13.4'

target 'Proyecto' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Proyecto
	pod 'Firebase/Analytics'
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'
	pod 'Firebase/Auth'

  target 'ProyectoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProyectoUITests' do
    # Pods for testing

  end

end
